CREATE TABLE IF NOT EXISTS `customer` (
  id BINARY(16) NOT NULL,
  `email` VARCHAR(255) NOT NULL UNIQUE,
  `pwd` VARCHAR(255) NOT NULL NULL,
  `role` VARCHAR(255) NOT NULL NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
